
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: myapp_development

 
test:
  <<: *default
  database: myapp_test

#production:
#  primary: &primary_production
#    <<: *default
#    database: myapp_production
#    username: myapp
#    password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
#  cache:
#    <<: *primary_production
#    database: myapp_production_cache
#    migrations_paths: db/cache_migrate
#  queue:
#    <<: *primary_production
#    database: myapp_production_queue
#    migrations_paths: db/queue_migrate
#  cable:
#    <<: *primary_production
#    database: myapp_production_cable
#    migrations_paths: db/cable_migrate

production:
  <<: *default
  url: postgresql://myapp_development:qSj2dBuvoN45VYL9E0AN3y7C48Am0xih@dpg-csmef81u0jms73e536ug-a/myapp_development_gzo5
  pool: 5
  timeout: 5000